{
	"version": 1630375443,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"HTML5 Files/images/play_btn-sheet0.png",
		"HTML5 Files/images/background_img-sheet0.png",
		"HTML5 Files/images/background_img-sheet1.png",
		"HTML5 Files/images/transition-sheet0.png",
		"HTML5 Files/images/score_font.png",
		"HTML5 Files/images/sound_btn-sheet0.png",
		"HTML5 Files/images/sound_btn-sheet1.png",
		"HTML5 Files/images/full_btn-sheet0.png",
		"HTML5 Files/images/full_btn-sheet1.png",
		"HTML5 Files/images/cards-sheet0.png",
		"HTML5 Files/images/particles.png",
		"HTML5 Files/images/particles2.png",
		"HTML5 Files/images/particles3.png",
		"HTML5 Files/images/exit_btn-sheet0.png",
		"HTML5 Files/images/time_font.png",
		"HTML5 Files/images/particles4.png",
		"HTML5 Files/images/particles5.png",
		"HTML5 Files/media/buttons.m4a",
		"HTML5 Files/media/buttons.ogg",
		"HTML5 Files/media/match.m4a",
		"HTML5 Files/media/match.ogg",
		"HTML5 Files/media/card.m4a",
		"HTML5 Files/media/card.ogg",
		"HTML5 Files/icon-16.png",
		"HTML5 Files/icon-32.png",
		"HTML5 Files/icon-114.png",
		"HTML5 Files/icon-128.png",
		"HTML5 Files/icon-256.png",
		"HTML5 Files/loading-logo.png"
	]
}